### ISSUE TITLE
Crash when click on Push Notification

### ISSUE THREAD

**Issue by c-karolpawlik** [mparticle-integrations/mparticle-android-integration-iterable#32]
Hi,

I faced an issue with one thing in your library. I'm using yours default Push handler. And on Android 12 when i click on the notification i received my app crashes.
I'm receiving Push notifications with default handler embedded in library.

The exception i got:
```
Fatal Exception: java.lang.RuntimeException
Unable to start receiver com.iterable.iterableapi.IterablePushActionReceiver: java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from com.my.app.test (p
id=5319, uid=10146) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.`

       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4321)
       at android.app.ActivityThread.access$1600(ActivityThread.java:247)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7842)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)


Caused by java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from com.my.app.test  (pid=5319, uid=10146) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
       at android.os.Parcel.createException(Parcel.java:2409)
       at android.os.Parcel.readException(Parcel.java:2392)
       at android.os.Parcel.readException(Parcel.java:2334)
       at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5665)
       at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1177)
       at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:479)
       at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:479)
       at com.iterable.iterableapi.IterablePushActionReceiver.onReceive(IterablePushActionReceiver.java:32)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4312)
       at android.app.ActivityThread.access$1600(ActivityThread.java:247)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7842)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskManagerService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:2955)
	at com.android.server.wm.ActivityTaskManagerService.access$900(ActivityTaskManagerService.java:294)
	at com.android.server.wm.ActivityTaskManagerService$LocalService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:5309)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13183)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:12752)
```

It looks more like something from yours dependency from iterable SDK. But when they fix the crash I will need your library updated. I opened issue in the iterable project here -> [ISSUE](https://github.com/Iterable/iterable-android-sdk/issues/423)

**Comment by willpassidomo** [comment]
Hey @c-karolpawlik I saw that Iterable fixed this in their last release, I will update it right now and include it in our next release. Thanks for the report!

**Comment by willpassidomo** [comment]
I just merged it [here](https://github.com/mparticle-integrations/mparticle-android-integration-iterable/pull/30), our normal release is on Wednesday but I will notify you if it comes earlier or later

**Comment by c-karolpawlik** [comment]
@willpassidomo Thanks a lot for quick reaction and answer
